-- 5월 식품들의 총매출 조회하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131117
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM 
    FOOD_PRODUCT P INNER JOIN FOOD_ORDER O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY 
    TOTAL_SALES DESC, PRODUCT_ID;
