-- 자동차 대여 기록 별 대여 금액 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/151141
SELECT
    A.HISTORY_ID,
    ROUND(A.DAILY_FEE * A.DATEDIFF * ((100-COALESCE(P.DISCOUNT_RATE,0))/100),0) AS FEE
FROM(
SELECT 
    H.HISTORY_ID,
    C.CAR_ID,
    C.DAILY_FEE,
    DATEDIFF(END_DATE, START_DATE) + 1 AS DATEDIFF,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE 0
    END AS DURATION_TYPE
FROM 
    CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE = '트럭'
) A LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON A.DURATION_TYPE = P.DURATION_TYPE
WHERE
    P.CAR_TYPE IS NULL 
    OR P.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC,
    HISTORY_ID DESC;
