-- 저자 별 카테고리 별 매출액 집계하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/144856
WITH JAN_BOOK_SALES AS(
SELECT *
FROM BOOK_SALES
WHERE 
    SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
ORDER BY BOOK_ID
)
SELECT 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(TOTAL_PRICE) AS TOTAL_SALES
FROM AUTHOR A INNER JOIN (
SELECT 
    B.CATEGORY,
    B.AUTHOR_ID,
    B.PRICE * J.SALES AS TOTAL_PRICE
FROM 
    BOOK B INNER JOIN JAN_BOOK_SALES J
    ON B.BOOK_ID = J.BOOK_ID
ORDER BY
    B.BOOK_ID
) B ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY
    A.AUTHOR_ID,
    B.CATEGORY DESC;
