-- 주문량이 많은 아이스크림들 조회하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/133027
WITH SHIPMENT_TOTAL AS(
SELECT 
    FLAVOR,
    SUM(TOTAL_ORDER) AS SHIPMENT_TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR
)
SELECT
    F.FLAVOR
FROM 
    FIRST_HALF F INNER JOIN SHIPMENT_TOTAL S
    ON F.FLAVOR = S.FLAVOR
ORDER BY 
    F.TOTAL_ORDER + S.SHIPMENT_TOTAL_ORDER DESC
LIMIT 3;
