-- 상품을 구매한 회원 비율 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131534
WITH USER2021 AS 
(SELECT USER_ID
FROM USER_INFO
WHERE YEAR(JOINED) = 2021)

SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT * FROM USER2021)
GROUP BY 
    YEAR(SALES_DATE),
    MONTH(SALES_DATE)
ORDER BY YEAR, MONTH
